//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_MVC.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class chartDimension
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public chartDimension()
        {
            this.chartDimensionCardinalities = new HashSet<chartDimensionCardinality>();
            this.dimensionContexts = new HashSet<dimensionContext>();
        }
    
        public int ID { get; set; }
        public Nullable<int> chartID { get; set; }
        public Nullable<int> dimensionIndex { get; set; }
        public Nullable<int> isContinuous { get; set; }
    
        public virtual chart chart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chartDimensionCardinality> chartDimensionCardinalities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dimensionContext> dimensionContexts { get; set; }
    }
}
