//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_MVC.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class countryData
    {
        public int ID { get; set; }
        public string country { get; set; }
        public string countryCode { get; set; }
        public string subContinent { get; set; }
        public string subContinentCode { get; set; }
        public string continent { get; set; }
        public string continentCode { get; set; }
    }
}
