//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_MVC.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class dimensionCount
    {
        public int ID { get; set; }
        public Nullable<int> chartID { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual chart chart { get; set; }
    }
}
