//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_MVC.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedBack
    {
        public int ID { get; set; }
        public Nullable<int> chartID { get; set; }
        public Nullable<int> tableID { get; set; }
        public Nullable<int> numOfDim { get; set; }
        public string intention { get; set; }
        public Nullable<int> dim1_IsContinuous { get; set; }
        public Nullable<int> dim1_Cardinality { get; set; }
        public string dim1_context { get; set; }
        public Nullable<int> dim2_IsContinuous { get; set; }
        public Nullable<int> dim2_Cardinality { get; set; }
        public string dim2_context { get; set; }
        public Nullable<int> dim3_IsContinuous { get; set; }
        public Nullable<int> dim3_Cardinality { get; set; }
        public string dim3_context { get; set; }
        public Nullable<int> dim4_IsContinuous { get; set; }
        public Nullable<int> dim4_Cardinality { get; set; }
        public string dim4_context { get; set; }
        public Nullable<int> dim5_IsContinuous { get; set; }
        public Nullable<int> dim5_Cardinality { get; set; }
        public string dim5_context { get; set; }
        public Nullable<int> dim6_IsContinuous { get; set; }
        public Nullable<int> dim6_Cardinality { get; set; }
        public string dim6_context { get; set; }
        public Nullable<int> dim7_IsContinuous { get; set; }
        public Nullable<int> dim7_Cardinality { get; set; }
        public string dim7_context { get; set; }
        public string recommendation { get; set; }
        public Nullable<int> rating { get; set; }
    
        public virtual chart chart { get; set; }
        public virtual table table { get; set; }
    }
}
