//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_MVC.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class visualizedDataFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public visualizedDataFile()
        {
            this.tables = new HashSet<table>();
        }
    
        public int ID { get; set; }
        public Nullable<int> parentFileID { get; set; }
        public string fileLocation { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual originalDataFile originalDataFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<table> tables { get; set; }
    }
}
